kind: Service
apiVersion: v1
metadata:
  name: anz-test
  namespace: technical-test
spec:
  selector:
    app: anz-test
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
