substitutions:
  _APP_NAME: anz-test

steps:
  - id: "Go Dependencies"
    name: mirror.gcr.io/library/golang
    args: ["go", "mod", "download"]
    dir: task-1
    env:
    - GO111MODULE=on
    - GOPROXY=https://proxy.golang.org
    volumes:
    - name: go-modules
      path: /go

  - id: "Go Tests"
    name: mirror.gcr.io/library/golang
    args: ["go", "test", "./..."]
    dir: task-1
    env:
    - GO111MODULE=on
    volumes:
    - name: go-modules
      path: /go

  - id: "Go Security"
    name: securego/gosec
    args: [".", "/"]
    dir: task-1
    volumes:
    - name: go-modules
      path: /go

  - id: "Build Image"
    name: "gcr.io/cloud-builders/docker"
    entrypoint: "./build.sh"
    dir: task-1
    env:
    - PROJECT_ID=$PROJECT_ID
    - CLOUDBUILD=true

  - id: "Push Image"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/${_APP_NAME}"]
    dir: task-1

images: ["gcr.io/$PROJECT_ID/${_APP_NAME}"]
