substitutions:
  _CLOUDSDK_COMPUTE_ZONE: australia-southeast1-b
  _CLOUDSDK_CONTAINER_CLUSTER: anz-test-cluster
  _APP_NAME: anz-test

steps:
  - id: "Go Dependencies"
    name: mirror.gcr.io/library/golang
    args: ["go", "mod", "download"]
    env:
    - GO111MODULE=on
    - GOPROXY=https://proxy.golang.org
    volumes:
    - name: go-modules
      path: /go

  - id: "Go Tests"
    name: mirror.gcr.io/library/golang
    args: ["go", "test", "./..."]
    env:
    - GO111MODULE=on
    volumes:
    - name: go-modules
      path: /go

  - id: "Go Security"
    name: securego/gosec
    args: [".", "/"]
    volumes:
    - name: go-modules
      path: /go

  - id: "Build Image"
    name: "gcr.io/cloud-builders/docker"
    entrypoint: "./build.sh"
    env:
    - PROJECT_ID=$PROJECT_ID
    - CLOUDBUILD=true

  - id: "Push Image"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/${_APP_NAME}"]

images: ["gcr.io/$PROJECT_ID/${_APP_NAME}"]
