apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: anz-test-autoscaler
  namespace: technical-test
  labels:
    app: anz-test
spec:
  scaleTargetRef:
    kind: Deployment
    name: anz-test
    apiVersion: apps/v1
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 75
